#!/bin/bash
set -eu # exit script on errors

echo "copy onemenu env"
rsync /home/git/www/wishlist/.env .

echo "> npm install..."
npm install

# build is done with github actions
# echo "> npm run build..."
# npm run build

export MAIN="server"
